# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roy Quilor - Product Designer
email: roy@quilor.com
description: Roy Quilor is a Product Designer currently based in the UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://quilor.com" # the base hostname & protocol for your site
twitter_username: royquilor
dribbble_username: royquilor
instagram_username: royquilor
github_username:  royquilor
linkedin_username: roy-quilor-0b78559

exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME,
  sass,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  readme.md
]

# Build settings
markdown: kramdown
